[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Display Safari name in rarity
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "if AUT.card_type == 'Enhanced' then card_type = localize{type = 'name_text', key = card.config.center.key, set = 'Enhanced'} end"
position = "before"
payload = """
if AUT.card_type == 'Joker' and card.config.center.rarity == 'poke_safari' then card_type = ({['poke_safari'] = 'Safari'})[card.config.center.rarity] end
"""
match_indent = true

# Localization color
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "legendary = G.C.RARITY[4],"
position = "after"
payload = "poke_safari = G.C.RARITY['poke_safari'],"
match_indent = true

# Pokemon only functionality
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if v.yes_pool_flag and not G.GAME.pool_flags[v.yes_pool_flag] then add = nil end"
position = "after"
payload = "if v.set == 'Joker' and not v.stage and pokermon_config and pokermon_config.pokemon_only then add = nil end"
match_indent = true

# Magikarp functionality
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if next(find_joker('Splash')) then"
position = "at"
payload = "if next(find_joker('Splash')) or next(find_joker('magikarp')) or next(find_joker('gyarados')) then"
match_indent = true

# Extra Booster Functionality
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "for i = 1, 2 do"
position = "at"
payload = "for i = 1, (G.GAME.modifiers.cry_booster_packs or G.GAME.modifiers.poke_booster_packs) or 2 do"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.added_to_deck = true"
position = "after"
payload = '''
if self.config.shiny_on_add then
  if G.GAME.modifiers.poke_booster_packs then
    G.GAME.modifiers.poke_booster_packs = G.GAME.modifiers.poke_booster_packs + 1
  else
    G.GAME.modifiers.poke_booster_packs = 3
  end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.added_to_deck = false"
position = "after"
payload = '''
if self.edition and self.edition.poke_shiny and G.jokers then
  G.GAME.modifiers.poke_booster_packs = G.GAME.modifiers.poke_booster_packs - 1
end
'''
match_indent = true

# Voucher functionality
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "local _size = self.ability.extra"
position = "after"
payload = '''
if self.ability.name:find("Pocket") and G.GAME.extra_pocket_picks and G.GAME.extra_pocket_picks > 0 then
  _size = _size + G.GAME.extra_pocket_picks
end
'''
match_indent = true
