[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Display Safari name in rarity
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "if AUT.card_type == 'Enhanced' then card_type = localize{type = 'name_text', key = card.config.center.key, set = 'Enhanced'} end"
position = "before"
payload = """
if AUT.card_type == 'Joker' and card.config.center.rarity == 'poke_safari' then card_type = ({['poke_safari'] = 'Safari'})[card.config.center.rarity] end
"""
match_indent = true

# Localization color
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "legendary = G.C.RARITY[4],"
position = "after"
payload = "poke_safari = G.C.RARITY['poke_safari'],"
match_indent = true

# Pokemon only functionality
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if v.yes_pool_flag and not G.GAME.pool_flags[v.yes_pool_flag] then add = nil end"
position = "after"
payload = "if v.set == 'Joker' and not v.stage and pokermon_config and pokermon_config.pokemon_only then add = nil end"
match_indent = true

# Magikarp functionality
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if next(find_joker('Splash')) then"
position = "at"
payload = "if next(find_joker('Splash')) or next(find_joker('magikarp')) or next(find_joker('gyarados')) then"
match_indent = true
